### PR TITLE
0.12.0-incubating release

### PR DESCRIPTION
**Pull request by shimamoto**
Oh, there isn't a development branch... use master

Checking document...

### CODE REVIEW

**Comment by shimamoto** [comment]
I have checked it works.
@takezoe Can you review this PR?

**Comment by pferrel** [comment]
@shimamoto @takezoe this does not support all the pio build options and so will not work if pio is built in a different way from this template. We need to document this at very least and solve the pio vs template mismatched options more fundamentally maybe by creating a sample template build that supports all `make-distribution` options. But I see problems with doing this too so not sure how to solve it.

**Comment by pferrel** [comment]
Also the build.sbt locks people into the latest versions of Spark, etc. So this template will no longer work with services installed with pio-0.11.0 including the Scala version. Existing users should be warned about this--do not upgrade pio unless you are willing to upgrade scala, and other services. In the case of ES it means wiping the meta store, which in turn means they must `pio export` before upgrading and `pio import` into new apps to get metadata re-created in ES5.

**Comment by pferrel** [comment]
Upgrading HDFS may also come with a conversion process if data is stored there. Not sure.

**Comment by takezoe** [comment]
@pferrel It looks to be impossible to solve in the current template mechanism. I believe that keeping templates for the latest and default stack is the best in the current mechanism. It might have to be documented to prevent confusion of users, or we might have to consider a solution to solve it, but I think it's an another topic in either case.

Anyway, this pull request looks good to me, so I'm going to merge. Is this all right with you?

**Comment by pferrel** [comment]
the PR is fine, but this can be solved partially with the current templates. For instance why not support both the previous defaults (those used in 0.11.0) AND the latest defaults. This could be by leaving 2 build.sbts in the project, one for 0.10.0, one for 0.11.0. Better yet @dszeto says we can now build with sbt, which means we can have the optional libs in a single build.sbt controlled by CLI.

**Comment by pferrel** [comment]
Making templates easier for users doing upgrades is extremely important IMO.

Getting them working with 0.12.0 is first priority and I for one appreciate @shimamoto and @takezoe taking this on. But we need to make this better for the future.

**Pull request closed without merging**
